import { jsPDF } from 'jspdf';
import { format, differenceInMinutes } from 'date-fns';
import { type Job } from './supabase';

export const generateJobPOC = (job: Job) => {
  const doc = new jsPDF();
  const primaryColor = '#39FF14';
  const secondaryColor = '#0B0F14';
  const textColor = '#1A1A1A';
  const mutedColor = '#666666';

  // --- Header ---
  doc.setFillColor(secondaryColor);
  doc.rect(0, 0, 210, 40, 'F');
  
  doc.setTextColor('#FFFFFF');
  doc.setFontSize(24);
  doc.text('NOKAEL', 20, 20);
  
  doc.setFontSize(10);
  doc.setTextColor(primaryColor);
  doc.text('CHAIN OF CUSTODY SYSTEM', 20, 28);
  
  doc.setTextColor('#FFFFFF');
  doc.text(`JOB REF: #${job.job_ref.toString().padStart(4, '0')}`, 150, 20);
  doc.text(`ISSUED: ${format(new Date(), 'PPP')}`, 150, 28);

  // --- Job Summary Section ---
  let y = 60;
  doc.setTextColor(textColor);
  doc.setFontSize(14);
  doc.text('Consignment Manifest', 20, y);
  
  y += 15;
  doc.setFontSize(10);
  doc.setTextColor(mutedColor);
  doc.text('Type:', 20, y);
  doc.setTextColor(textColor);
  doc.text(job.item_type.toUpperCase(), 60, y);
  
  y += 8;
  doc.setTextColor(mutedColor);
  doc.text('Urgency:', 20, y);
  doc.setTextColor(textColor);
  doc.text(job.urgency.toUpperCase(), 60, y);

  y += 8;
  doc.setTextColor(mutedColor);
  doc.text('Route:', 20, y);
  doc.setTextColor(textColor);
  doc.text(`${job.pickup_location} (${job.pickup_emirate})`, 60, y);
  y += 6;
  doc.text('to', 60, y);
  y += 6;
  doc.text(`${job.delivery_location} (${job.delivery_emirate})`, 60, y);

  y += 12;
  doc.setTextColor(mutedColor);
  doc.text('Deployment Pilot:', 20, y);
  doc.setTextColor(textColor);
  doc.text(job.driver_name || 'Unassigned', 60, y);

  // --- Chain of Custody Timeline ---
  y += 25;
  doc.setFontSize(14);
  doc.text('Chain of Custody (COC) Timeline', 20, y);
  
  y += 10;
  const steps = [
    { label: 'Sender Handover', time: job.client_pickup_confirmed_at, method: job.client_pickup_method, lat: job.client_pickup_lat, lng: job.client_pickup_lng },
    { label: 'Pilot Pickup', time: job.driver_pickup_confirmed_at, method: job.driver_pickup_method, lat: job.driver_pickup_lat, lng: job.driver_pickup_lng },
    { label: 'In-Transit Validation', time: job.driver_delivery_confirmed_at, method: job.driver_delivery_method, lat: job.driver_delivery_lat, lng: job.driver_delivery_lng },
    { label: 'Consignee Receipt', time: job.client_delivery_confirmed_at, method: job.client_delivery_method, lat: job.client_delivery_lat, lng: job.client_delivery_lng },
  ];

  steps.forEach((step, index) => {
    y += 15;
    doc.setFontSize(10);
    doc.setTextColor(step.time ? textColor : mutedColor);
    doc.text(`${index + 1}. ${step.label}`, 25, y);
    
    if (step.time) {
      doc.setFontSize(8);
      doc.setTextColor(mutedColor);
      const timeStr = format(new Date(step.time), 'PPP HH:mm:ss');
      const methodStr = `Method: ${step.method?.toUpperCase()}`;
      const geoStr = step.lat ? `GPS: ${step.lat.toFixed(4)}, ${step.lng.toFixed(4)}` : 'GPS: Not Captured';
      
      doc.text(`${timeStr}  |  ${methodStr}`, 30, y + 5);
      doc.text(geoStr, 30, y + 9);
      
      doc.setDrawColor(primaryColor);
      doc.setLineWidth(0.5);
      doc.line(20, y - 4, 20, y + 10);
    } else {
      doc.text('STAGED / WAITING', 30, y + 5);
    }
  });

  // --- Metrics ---
  if (job.client_pickup_confirmed_at && job.client_delivery_confirmed_at) {
    const transitMin = differenceInMinutes(new Date(job.client_delivery_confirmed_at), new Date(job.client_pickup_confirmed_at));
    y += 35;
    doc.setFillColor('#F0F0F0');
    doc.rect(20, y, 170, 20, 'F');
    doc.setTextColor(textColor);
    doc.setFontSize(10);
    doc.text('TOTAL TRANSIT PERFORMANCE:', 30, y + 12);
    doc.setFontSize(12);
    doc.text(`${transitMin} MINUTES`, 140, y + 12);
  }

  // --- Security Footer ---
  doc.setFontSize(8);
  doc.setTextColor(mutedColor);
  doc.text('Digital Chain of Custody generated by Nokael Internal Dispatch Command.', 105, 285, { align: 'center' });
  doc.text('This record is immutable and verified at each handover via unique sequence tokens.', 105, 290, { align: 'center' });

  doc.save(`Nokael-COC-Job-${job.job_ref}.pdf`);
};
